# Generated by Django 3.2.9 on 2021-11-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://cdn.pixabay.com/photo/2021/08/25/20/42/field-6574455__480.jpg', null=True, upload_to='uploads/'),
        ),
    ]
